# **Project 2 - Sales Analysis - ETL**

## Objectives

- Extract data from provided CSV files
- Clean it 
- Apply feature engineering if necessary 
- Remove any unnecessary columns
- Save to a new CSV file


## Inputs

CSV files provided:

stores data-set.csv
sales data-set.csv
features data set.csv

Renamed files to a uniform naming convention:

Sales_Features_DataSet.csv
Sales_DataSet.csv
Sales_Stores_DataSet.csv

Note: original files are stored in Data/OriginalFiles


## Outputs

CSV file created from ETL etc stored in Data:

Sales_Combined_DataSet.csv

## Additional Comments

Developed an experimental ETL library which is in this project (modETL_library.py) 
Has lots of cool features so will be interesting to see how it works "in the field"



Used various AI tools to help with the ETL process:
- ChatGPT
- GitHub Copilot. 

See Documents/What_AI_Used_For.md for more details.

## Initalise Working Environment

In [1]:
#import libraries
import os
import numpy as np
import pandas as pd

#below solution provided by chatGPT 
import sys
from pathlib import Path

project_root = Path.cwd().parent

if str(project_root / "assets" / "python_files") not in sys.path:
    sys.path.insert(0, str(project_root / "assets" / "python_files"))
    
import modGlobal
import modETL_Library as modETL
#end solution provided by chatGPT

# Section 1 - Initalisation

## Intitialise All Variables To Be Used In Global Stack

In [2]:
#DataFrame vars for ETL
dfSales_Features_DataSet = None
dfSales_Stores_DataSet = None
dfSales_DataSet = None
dfSales_Combined_DataSet = None

#stores current directory
strCurrentDir = ""

#other vars
intMissingPercent = 0
intMissing = 0
dictDataFrames = dict()
lstColumns = list()

## Set Current Directory To Base Project Directory

In [3]:
#get project directory - default is jupyter notebook sub folder as that is where this file is located!
#so move back one to the project root path
# Source - https://stackoverflow.com/a/17726833
# Posted by chimpsarehungry
# Retrieved 2026-07-05, License - CC BY-SA 3.0

#get current folder
strCurrentDir = os.getcwd()

#is the last part of the path the project directory?
if not strCurrentDir.endswith(modGlobal.CNST_STR_PROJECT_DIR):
   #get current working directory and move back one to the project root path
   strCurrentDir =  os.path.normpath(os.getcwd() + os.sep + os.pardir)
   os.chdir(os.path.dirname(strCurrentDir))
   #change directory
   os.chdir(strCurrentDir)

#confirm current directory is project directory
print(f"Current Directory: \n {os.getcwd()}")

Current Directory:
 /Users/rogerwilliams/Projects/Python/CourseProjects/Project2-SalesAnalysis

# Section 1 - Combination

- Read csv files
- Combine into one DataFrame

## Read csv Files Into Variable For Processing

In [4]:
#read csv files into DataFrames
#ETL library returns a dictionary of all files in the folder with the attribute name
#set to the actual csv filename
dictDataFrames = modETL.funcReadVisualisationFilesReturnDictionary()
dfSales_DataSet = dictDataFrames["Sales_DataSet_Visualisation.csv"]
dfSales_Features_DataSet = dictDataFrames["Features_DataSet_Visualisation.csv"]
dfSales_Stores_DataSet = dictDataFrames["Stores_DataSet_Visualisation.csv"]

4 csv Files Read Into DataFrames

DataFrames Created:
Sales_Combined_DataSet_Visualisation.csv
Features_DataSet_Visualisation.csv
Sales_DataSet_Visualisation.csv
Stores_DataSet_Visualisation.csv

## Combine The Data Frames!

## How The DataFrames Are Related

_"primary key"_  
dfSales_Stores_DataSet Has One Common Column: Store  
dfSales_DataSet Has One Common Column With dfSales_Stores_DataSet: Store  
dfSales_Features_DataSet Has One Common Column With dfSales_Stores_DataSet: Store  

_Columns Shared Between dfSales_DataSet And dfSales_Features_DataSet:_    
Store, Date

Combined Columns To Use For Analysis:  
Store: int64  
Date: datetime64[us]  
Size: int64  
Temperature: float64  
Dept: int64. 
Weekly_Sales: float64  
IsHoliday: bool  
MarkDown1: float64  
MarkDown2: float64  
MarkDown3: float64  
MarkDown4: float64  
MarkDown5: float64  
StoreType: int64 <- Feature Engineering addition to Sales_Stores_DataSet.csv>

In [5]:
#first convert the Date columns to datetime format
dfSales_DataSet["Date"] = pd.to_datetime(dfSales_DataSet["Date"], format="%d/%m/%Y")
dfSales_Features_DataSet["Date"] = pd.to_datetime(dfSales_Features_DataSet["Date"], format="%d/%m/%Y")

#combine DataFrames
dfSales_Combined_DataSet = pd.merge(dfSales_DataSet, dfSales_Features_DataSet, on=['Store', 'Date'], how='inner')

# Merge Sales and Features
dfSales_Combined_DataSet = pd.merge(
    dfSales_DataSet,
    dfSales_Features_DataSet,
    on=["Store", "Date"],
    how="inner",
    indicator = True
)

# Merge the result with Stores
dfSales_Combined_DataSet = pd.merge(
    dfSales_Combined_DataSet,
    dfSales_Stores_DataSet,
    on="Store",
    how="inner"
)

#show results need huge value so we can check data against the original data sets
dfSales_Combined_DataSet.head(100000)

,Unnamed: 0_x,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Unnamed: 0_y,Temperature,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,IsHoliday_y,Unemployment,_merge,Unnamed: 0,Size,Store_Type
0,0,1,1,2010-02-05,24924.50,False,0,42.31,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1
1,1,1,1,2010-02-12,46039.49,True,1,38.51,0.0,0.0,0.0,0.0,0.0,True,8.106,both,0,151315,1
2,2,1,1,2010-02-19,41595.55,False,2,39.93,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1
3,3,1,1,2010-02-26,19403.54,False,3,46.63,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1
4,4,1,1,2010-03-05,21827.90,False,4,46.50,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,11,17,2010-04-23,13984.63,False,1831,68.37,0.0,0.0,0.0,0.0,0.0,False,7.343,both,10,207499,1
99996,99996,11,17,2010-04-30,10486.69,False,1832,71.13,0.0,0.0,0.0,0.0,0.0,False,7.343,both,10,207499,1
99997,99997,11,17,2010-05-07,12840.19,False,1833,75.57,0.0,0.0,0.0,0.0,0.0,False,7.343,both,10,207499,1
99998,99998,11,17,2010-05-14,11494.95,False,1834,77.64,0.0,0.0,0.0,0.0,0.0,False,7.343,both,10,207499,1
99999,99999,11,17,2010-05-21,12693.72,False,1835,76.97,0.0,0.0,0.0,0.0,0.0,False,7.343,both,10,207499,1

## Observations - Sales_Combined_DataSet

Checks:

Checked Column value change for Markdown1 at page: 81 to check if had value: 10382.9
as per the raw csv file.

Checked column value change for Store at page: 2049 to check if StoreType column
was correctly showing the value 2 when the Store column value was 3 as in the 
dfSales_Store_DataSet DataFrame Store value 3 = store type B which in the new column
added during data transformation in Notebook_ETL_Sales_Stores_DataSet.ipynb is 2

All values found as expected.

Note: In Features data set.csv there is 7 months of data NOT in sales data-set.csv so needed 
      to filter that out of the results

## Observations - Sales_Combined_DataSet
Check new DataFrame schema

In [6]:
#check new DataFrame schema
dfSales_Combined_DataSet.dtypes

Unnamed: 0_x             int64
Store                    int64
Dept                     int64
Date            datetime64[us]
Weekly_Sales           float64
IsHoliday_x               bool
Unnamed: 0_y             int64
Temperature            float64
MarkDown1              float64
MarkDown2              float64
MarkDown3              float64
MarkDown4              float64
MarkDown5              float64
IsHoliday_y               bool
Unemployment           float64
_merge                category
Unnamed: 0               int64
Size                     int64
Store_Type               int64
dtype: object

## Observations - Sales_Combined_DataSet

Columns count correct, need to rename some other like Unnamed will simply be excluded from
addition to the cleaned csv

---

# Section 2 - Transformation

- Rename any columns if necessary

Columns To Rename:  
IsHoliday_x -> IsHoliday  
Size -> Store_Size

## Observations - Rename Columns

In [7]:
#rename columns: IsHoliday_x -> IsHoliday   Size_x -> Store_Size
dfSales_Combined_DataSet.rename(columns={'IsHoliday_x': 'IsHoliday', 'Size': 'Store_Size'}, inplace=True)

#check results
dfSales_Combined_DataSet.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 19 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0_x  421570 non-null  int64
 1   Store         421570 non-null  int64
 2   Dept          421570 non-null  int64
 3   Date          421570 non-null  datetime64[us]
 4   Weekly_Sales  421570 non-null  float64
 5   IsHoliday     421570 non-null  bool
 6   Unnamed: 0_y  421570 non-null  int64
 7   Temperature   421570 non-null  float64
 8   MarkDown1     421570 non-null  float64
 9   MarkDown2     421570 non-null  float64
 10  MarkDown3     421570 non-null  float64
 11  MarkDown4     421570 non-null  float64
 12  MarkDown5     421570 non-null  float64
 13  IsHoliday_y   421570 non-null  bool
 14  Unemployment  421570 non-null  float64
 15  _merge        421570 non-null  category
 16  Unnamed: 0    421570 non-null  int64
 17  Store_Size    421570 non-null  int64
 18  Store_Type    421570 non-null  int64
dtypes: bool(2), category(1), datetime64[us](1), float64(8), int64(7)
memory usage: 52.7 MB

## Observations - Combined_DataSet

Schema as expected

## Check For Missing Values (Paranoia)

In [8]:
#get total missing values
intMissing = dfSales_Combined_DataSet.isnull().sum()

#calculate percent missing
intMissingPercent = ( intMissing / len(dfSales_Combined_DataSet) * 100)
dfCheck = pd.DataFrame( {"Missing Values": intMissing, "%" : intMissingPercent})

#show results
if dfCheck["Missing Values"].sum() !=0:
   print( dfCheck[dfCheck["Missing Values"] > 0])
else:
   print( "No Missing Values")

No Missing Values

## Observations - Combined_DataSet

No Missing Values - Phew!

---

## Data Transformations/Feature Engineering

Had Mad Scientist idea:

Create a column with just year and month in it, if I get time (and if its actually feasible)
Might be able to knock some visualsations by month...

In [9]:
#create a column with JUST year and month as integer
dfSales_Combined_DataSet["YearMonth"] = dfSales_Combined_DataSet["Date"].dt.strftime('%Y%m').astype(int)

#check results
dfSales_Combined_DataSet.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 20 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0_x  421570 non-null  int64
 1   Store         421570 non-null  int64
 2   Dept          421570 non-null  int64
 3   Date          421570 non-null  datetime64[us]
 4   Weekly_Sales  421570 non-null  float64
 5   IsHoliday     421570 non-null  bool
 6   Unnamed: 0_y  421570 non-null  int64
 7   Temperature   421570 non-null  float64
 8   MarkDown1     421570 non-null  float64
 9   MarkDown2     421570 non-null  float64
 10  MarkDown3     421570 non-null  float64
 11  MarkDown4     421570 non-null  float64
 12  MarkDown5     421570 non-null  float64
 13  IsHoliday_y   421570 non-null  bool
 14  Unemployment  421570 non-null  float64
 15  _merge        421570 non-null  category
 16  Unnamed: 0    421570 non-null  int64
 17  Store_Size    421570 non-null  int64
 18  Store_Type    421570 non-null  int64
 19  YearMonth     421570 non-null  int64
dtypes: bool(2), category(1), datetime64[us](1), float64(8), int64(8)
memory usage: 55.9 MB

## Observations - Combined_DataSet

Schema as expected

## Check Data In New Column

In [10]:
#check data
dfSales_Combined_DataSet.head(50)

,Unnamed: 0_x,Store,Dept,Date,Weekly_Sales,IsHoliday,Unnamed: 0_y,Temperature,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,IsHoliday_y,Unemployment,_merge,Unnamed: 0,Store_Size,Store_Type,YearMonth
0,0,1,1,2010-02-05,24924.50,False,0,42.31,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201002
1,1,1,1,2010-02-12,46039.49,True,1,38.51,0.0,0.0,0.0,0.0,0.0,True,8.106,both,0,151315,1,201002
2,2,1,1,2010-02-19,41595.55,False,2,39.93,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201002
3,3,1,1,2010-02-26,19403.54,False,3,46.63,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201002
4,4,1,1,2010-03-05,21827.90,False,4,46.50,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201003
5,5,1,1,2010-03-12,21043.39,False,5,57.79,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201003
6,6,1,1,2010-03-19,22136.64,False,6,54.58,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201003
7,7,1,1,2010-03-26,26229.21,False,7,51.45,0.0,0.0,0.0,0.0,0.0,False,8.106,both,0,151315,1,201003
8,8,1,1,2010-04-02,57258.43,False,8,62.27,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201004
9,9,1,1,2010-04-09,42960.91,False,9,65.86,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201004
10,10,1,1,2010-04-16,17596.96,False,10,66.32,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201004
11,11,1,1,2010-04-23,16145.35,False,11,64.84,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201004
12,12,1,1,2010-04-30,16555.11,False,12,67.41,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201004
13,13,1,1,2010-05-07,17413.94,False,13,72.55,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201005
14,14,1,1,2010-05-14,18926.74,False,14,74.78,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201005
15,15,1,1,2010-05-21,14773.04,False,15,76.44,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201005
16,16,1,1,2010-05-28,15580.43,False,16,80.44,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201005
17,17,1,1,2010-06-04,17558.09,False,17,80.69,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201006
18,18,1,1,2010-06-11,16637.62,False,18,80.43,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201006
19,19,1,1,2010-06-18,16216.27,False,19,84.11,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201006
20,20,1,1,2010-06-25,16328.72,False,20,84.34,0.0,0.0,0.0,0.0,0.0,False,7.808,both,0,151315,1,201006
21,21,1,1,2010-07-02,16333.14,False,21,80.91,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201007
22,22,1,1,2010-07-09,17688.76,False,22,80.48,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201007
23,23,1,1,2010-07-16,17150.84,False,23,83.15,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201007
24,24,1,1,2010-07-23,15360.45,False,24,83.36,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201007
25,25,1,1,2010-07-30,15381.82,False,25,81.84,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201007
26,26,1,1,2010-08-06,17508.41,False,26,87.16,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201008
27,27,1,1,2010-08-13,15536.40,False,27,87.00,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201008
28,28,1,1,2010-08-20,15740.13,False,28,86.65,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201008
29,29,1,1,2010-08-27,15793.87,False,29,85.22,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201008
30,30,1,1,2010-09-03,16241.78,False,30,81.21,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201009
31,31,1,1,2010-09-10,18194.74,True,31,78.69,0.0,0.0,0.0,0.0,0.0,True,7.787,both,0,151315,1,201009
32,32,1,1,2010-09-17,19354.23,False,32,82.11,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201009
33,33,1,1,2010-09-24,18122.52,False,33,80.94,0.0,0.0,0.0,0.0,0.0,False,7.787,both,0,151315,1,201009
34,34,1,1,2010-10-01,20094.19,False,34,71.89,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201010
35,35,1,1,2010-10-08,23388.03,False,35,63.93,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201010
36,36,1,1,2010-10-15,26978.34,False,36,67.18,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201010
37,37,1,1,2010-10-22,25543.04,False,37,69.86,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201010
38,38,1,1,2010-10-29,38640.93,False,38,69.64,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201010
39,39,1,1,2010-11-05,34238.88,False,39,58.74,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201011
40,40,1,1,2010-11-12,19549.39,False,40,59.61,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201011
41,41,1,1,2010-11-19,19552.84,False,41,51.41,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201011
42,42,1,1,2010-11-26,18820.29,True,42,64.52,0.0,0.0,0.0,0.0,0.0,True,7.838,both,0,151315,1,201011
43,43,1,1,2010-12-03,22517.56,False,43,49.27,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201012
44,44,1,1,2010-12-10,31497.65,False,44,46.33,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201012
45,45,1,1,2010-12-17,44912.86,False,45,49.84,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201012
46,46,1,1,2010-12-24,55931.23,False,46,52.33,0.0,0.0,0.0,0.0,0.0,False,7.838,both,0,151315,1,201012
47,47,1,1,2010-12-31,19124.58,True,47,48.43,0.0,0.0,0.0,0.0,0.0,True,7.838,both,0,151315,1,201012
48,48,1,1,2011-01-07,15984.24,False,48,48.27,0.0,0.0,0.0,0.0,0.0,False,7.742,both,0,151315,1,201101
49,49,1,1,2011-01-14,17359.70,False,49,35.40,0.0,0.0,0.0,0.0,0.0,False,7.742,both,0,151315,1,201101

## Observations - Combined_DataSet

Data as expected

## Save Combined DataFrame To CSV File

In [11]:
print(dfSales_Combined_DataSet["Date"])

0        2010-02-05
1        2010-02-12
2        2010-02-19
3        2010-02-26
4        2010-03-05
            ...
421565   2012-09-28
421566   2012-10-05
421567   2012-10-12
421568   2012-10-19
421569   2012-10-26
Name: Date, Length: 421570, dtype: datetime64[us]

In [12]:
#create list of columns new and old JUST what is actually needed
lstColumns = [
                #columns to use in the cleaned file (excludes any index)
                "Store","Dept","Date","Weekly_Sales","IsHoliday",
                "MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5",
                "Store_Type","Store_Size","Temperature","Unemployment",
                "YearMonth"
               ]

#create new DataFrame for cleaned data
dfCleaned = dfSales_Combined_DataSet[lstColumns].copy()
dfCleaned.attrs["name"] = "Sales_Combined_DataSet_Working"

modETL.funcSaveDataFrameToCleanedFile(dfCleaned)

#Note: excluded column: Dept as not in the hypothesis analysis which is a nice way
#      avoiding the fact I don't know just how to plot a chart with 98 departments
#      and have it readable!

Saved: Sales_Combined_DataSet To Visualisation Folder

# Next Steps

End of ETL process. Now visualising the hypothesis can begin!

See notebook:
Notebook_Visualisations.jpynb